# build environment
FROM node:lts-alpine3.14@sha256:7964eefba059e1536cca5c8da0181457b62d32f88a66fa44cb52734cd3b28c29 AS builder
LABEL enjoty.webapp.name=enjoty_frontend_app
LABEL enjoty.webapp.builder=true
WORKDIR /usr/src/enjotywebapp
ENV PATH /usr/src/enjotywebapp/node_modules/.bin:$PATH
##COPY package*.json tsconfig.json ./
RUN npm install
RUN npm ci --silent --only=production
ENV NODE_ENV production
COPY . .
RUN npm run build

# production environment
FROM nginx:1.21.1-alpine@sha256:bfe377bdeb9ff37a62b49e149ac12c67a18089699bb844ce917fe3dbb834abed AS production
LABEL enjoty.webapp.name=enjoty_frontend_app
ENV NODE_ENV production
COPY /docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /usr/src/enjotywebapp/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
